/* Population with given users, where:
	-Username is their first initial followed by full last name
    -Password has additional salt1...salt44 */
INSERT INTO users(user_name, first_name, last_name, email, encrypted_password, salt, user_state_id, dept_id) 
VALUES ('amahadev', 'Aparna', 'Mahadev', 'amahadev@wpi.edu', 'passwordsalt1', 'salt1', '1', '6'), 
('kahmedul', 'Kabir', 'Ahmedul', 'kahmedul@wpi.edu', 'passwordsalt2', 'salt2', '1', '6'),
('bnelson', 'Blake', 'Nelson', 'bnelson@wpi.edu', 'passwordsalt3', 'salt3', '1', '6'),
('cwills', 'Craig', 'Wills', 'cwills@wpi.edu', 'passwordsalt4', 'salt4', '2', '6' ),
('ckngan', 'Chun-Kit', 'Ngan', 'ckngan@wpi.edu', 'passwordsalt5', 'salt5', '1', '6' ),
('cruiz', 'Carolina', 'Ruiz', 'cruiz@wpi.edu', 'passwordsalt6', 'salt6', '1', '6'),
('crich', 'Charles', 'Rich', 'crich@wpi.edu', 'passwordsalt7', 'salt7', '1', '6'),
('cshue', 'Craig', 'Shue', 'cshue@wpi.edu', 'passwordsalt8', 'salt8', '1', '6'),
('cpinciroli', 'Carlo', 'Pinciroli', 'cpinciroli@wpi.edu', 'passwordsalt9', 'salt9', '1', '6'),
('ddougherty', 'Dan', 'Dougherty', 'ddougherty@wpi.edu', 'passwordsalt10', 'salt10', '1', '6'),
('dkorkin', 'Dmitry', 'Korkin', 'dkorkin@wpi.edu', 'passwordsalt11', 'salt11', '1', '6'),
('dselent', 'Doug', 'Selent', 'dselent@wpi.edu', 'passwordsalt12', 'salt12', '1', '6'),
('erundensteiner', 'Elke', 'Rundensteiner', 'erundensteiner@wpi.edu', 'passwordsalt13', 'salt13', '1', '6'),
('eagu', 'Emmanuel', 'Agu', 'eagu@wpi.edu', 'passwordsalt14', 'salt14', '1', '6'),
('gpollice', 'Gary', 'Pollice', 'gpollice@wpi.edu', 'passwordsalt15', 'salt15', '1', '6'),
('ghamel', 'Glynis', 'Hamel', 'ghamel@wpi.edu', 'passwordsalt16', 'salt16', '1', '6'),
('gheineman', 'George', 'Heineman', 'gheineman@wpi.edu', 'passwordsalt17', 'salt17', '1', '6'),
('gsarkozy', 'Gabor', 'Sarkozy', 'gsarkozy@wpi.edu', 'passwordsalt18', 'salt18', '1', '6'),
('hloi', 'Hao', 'Loi', 'hloi@wpi.edu', 'passwordsalt19', 'salt19', '1', '6'),
('hlauer', 'Hugh', 'Lauer', 'hlauer@wpi.edu', 'passwordsalt20', 'salt20', '1', '6'),
('hservatius', 'Herman', 'Servatius', 'hservatius@wpi.edu', 'passwordsalt21', 'salt21', '1', '6'),
('jbeck', 'Joe', 'Beck', 'jbeck@wpi.edu', 'passwordsalt22', 'salt22', '1', '6'),
('jbreecher', 'Jerry', 'Breecher', 'jbreecher@wpi.edu', 'passwordsalt23', 'salt23', '1', '6'),
('jcuneo', 'Joshua', 'Cuneo', 'jcuneo@wpi.edu', 'passwordsalt24', 'salt24', '1', '6'),
('jsingh', 'J.', 'Singh', 'jsingh@wpi.edu', 'passwordsalt25', 'salt25', '1', '6'),
('jtoro', 'Jorge', 'Toro', 'jtoro@wpi.edu', 'passwordsalt26', 'salt26', '1', '6'),
('jwhitehill', 'Jacob', 'Whitehill', 'jwhitehill@wpi.edu', 'passwordsalt27', 'salt27', '1', '6'),
('kvenkatasubramanian', 'Krishna', 'Venkatasubramanian','kvenkatasubramanian@wpi.edu', 'passwordsalt28', 'salt28', '1', '6'),
('kpray', 'Keith', 'Pray', 'kpray@wpi.edu', 'passwordsalt29', 'salt29', '1', '6' ),
('lharrison', 'Lane', 'Harrison', 'lharrison@wpi.edu', 'passwordsalt30', 'salt30', '1', '6'),
('mhofri', 'Micha', 'Hofri', 'mhofri@wpi.edu', 'passwordsalt31', 'salt31', '1', '6'),
('mclaypool', 'Mark', 'Claypool', 'mclaypool@wpi.edu', 'passwordsalt32', 'salt32', '1', '6'),
('mciaraldi', 'Mike', 'Ciaraldi', 'mciaraldi@wpi.edu', 'passwordsalt33', 'salt33', '1', '6'),
('mgennert', 'Mike', 'Gennert', 'mgennert@wpi.edu', 'passwordsalt34', 'salt34', '1', '6'),
('meltabakh', 'Mohamed', 'Eltabakh', 'meltabakh@wpi.edu', 'passwordsalt35', 'salt35', '1', '6'),
('nheffernan', 'Neil', 'Heffernan', 'nhefferman@wpi.edu', 'passwordsalt36', 'salt36', '1', '6'),
('rwalls', 'Robert', 'Walls', 'rwalls@wpi.edu', 'passwordsalt37', 'salt37', '1', '6'),
('rneamtu', 'Rodica', 'Neamtu', 'rneamtu@wpi.edu', 'passwordsalt38', 'salt38', '1', '6'),
('smstark', 'Suzanne', 'Mello-Stark', 'smstark@wpi.edu', 'passwordsalt39', 'salt39', '1', '6'),
('slandau', 'Susan', 'Landau', 'slandau@wpi.edu', 'passwordsalt40', 'salt40', '1', '6'),
('tguo', 'Tian', 'Guo', 'tguo@wpi.edu', 'passwordsalt41', 'salt41', '1', '6'),
('wwong', 'Wilson', 'Wong', 'wwong@wpi.edu', 'passwordsalt42', 'salt42', '1', '6'),
('yli', 'Yanhua', 'Li', 'yli@wpi.edu', 'passwordsalt43', 'salt43', '1', '6');

/* Insert Courses statements */
INSERT INTO courses (name, course_abrv, dept_id, course_number)
VALUES ('Introduction to Programming for Non-Majors', 'CS', 6, '1004'),
('Introduction to Program Design', 'CS', 6, '1101'),
('Accelerated Introduction to Program Design', 'CS', 6, '1102'),
('Introduction to Machine Organization and Assembly Language', 'CS', 6, '2011'),
('Discrete Mathematics', 'CS', 6, '2022'),
('Object-Oriented Design Concepts', 'CS', 6, '2102'),
('Application Building with Object-Oriented Concepts', 'CS', 6, '2119'),
('Algorithms', 'CS', 6, '2223'),
('Systems Programming for Non-Majors', 'CS', 6, '2301'),
('Systems Programming Concepts', 'CS', 6, '2303'),
('Operating Systems', 'CS', 6, '3013'),
('Human-Computer Interaction', 'CS', 6, '3041'),
('Social Implications of Information Processing', 'CS', 6, '3043'),
('Foundations of Computer Science', 'CS', 6, '3133'),
('Database Systems I', 'CS', 6, '3431'),
('Computer Networks', 'CS', 6, '3516'),
('Software Engineering', 'CS', 6, '3733'),
('Numerical Methods for Linear and Nonlinear Systems', 'CS', 6, '4032'),
('Numerical Methods for Calculus and Differential Equations', 'CS', 6, '4033'),
('Artificial Intelligence for Interactive Media and Games', 'CS', 6, '4100'),
('Analysis of Algorithms', 'CS', 6, '4120'),
('Theory of Computation', 'CS', 6, '4123'),
('Object-Oriented Analysis and Design', 'CS', 6, '4233'),
('Webware: Computational Technology for Network Information Systems', 'CS', 6, '4241'),
('Introduction to Artificial Intelligence', 'CS', 6, '4341'),
('Software Security Engineering', 'CS', 6, '4401'),
('Database Systems II', 'CS', 6, '4432'),
('Data Mining and Knowledge Discovery in Databases', 'CS', 6, '4445'),
('Distributed Computer Systems', 'CS', 6, '4513'),
('Mobile and Ubiquitous Computing', 'CS', 6, '4518'),
('Programming Languages', 'CS', 6, '4536'),
('Computer Graphics', 'CS', 6, '4731'),
('Introduction to Cryptography and Communication Security', 'CS', 6, '4801'),
('Biovisualization', 'CS', 6, '4802'),
('Biological and Biomedical Database Mining', 'CS', 6, '4803'),
('Accelerated Object-Oriented Design Concepts', 'CS', 6, '210X'),
('Machine Learning', 'CS', 6, '453X'),
('Operating Systems', 'CS', 6, '502'),
('Foundations of Computer Science', 'CS', 6, '503'),
('Design of Software Systems', 'CS', 6, '509'),
('Computer Networks', 'CS', 6, '513'),
('Numerical Methods', 'CS', 6, '522'),
('Topics in Computer Science', 'CS', 6, '525'),
('Mobile and Ubiquitous Computing', 'CS', 6, '528'),
('Artificial Intelligence', 'CS', 6, '534'),
('Machine Learning', 'CS', 6, '539'),
('Database Management Systems', 'CS', 6, '542'),
('Computer Graphics', 'CS', 6, '543'),
('Knowledge Discovery and Data Mining', 'CS', 6, '548'),
('Computer Vision', 'CS', 6, '549'),
('Computer Network Security', 'CS', 6, '558'),
('User Modeling', 'CS', 6, '565'),
('Case Studies in Computer Security', 'CS', 6, '571'),
('Data Visualization', 'CS', 6, '573'),
('Cryptography and Data Security', 'CS', 6, '578'),
('Biovisualization', 'CS', 6, '582'),
('Biological and Biomedical Database Mining', 'CS', 6, '583'),
('Algorithms: Design and Analysis', 'CS', 6, '584'),
('Big Data Management', 'CS', 6, '585'),
('Big Data Analytics', 'CS', 6, '586'),
('Foundations of Computer Science: An Introduction', 'CS', 6, '5003'),
('Introduction to Programming Concepts, Data Structures and Algorithms', 'CS', 6, '5007'),
('Introduction to Algorithms: Design and Analysis', 'CS', 6, '5084');

/* Insert Sections statements */
INSERT INTO sections (course_id, crn, section_name, section_id, expected_population, required_frequency, academic_year, academic_term, start_time, end_time, days_per_week, course_location)
VALUES ('1', '10123', 'A01', '1', '50', '4', '2018', 'A', '1000', '1100', 'MTRF', 'AK 116'), ('1', '10124', 'A02', '1', '50', '4', '2018', 'A', '1200', '1300', 'MTRF', 'AK 116'),
('1', '10125', 'A03', '1', '50', '4', '2018', 'A', '1600', '1700', 'MTRF', 'AK 116'), ('2', '10126', 'B01', '1', '50', '4', '2018', 'B', '1000', '1100', 'MTRF', 'SL 106'),
('2', '10227', 'B02', '1', '50', '4', '2018', 'B', '1200', '1300', 'MTRF', 'SL 106'), ('3', '10128', 'C01', '1', '50', '4', '2018', 'C', '1000', '1100', 'MTRF', 'SL 106'),
('4', '10129', 'D01', '1', '80', '4', '2018', 'D', '1300', '1500', 'MTRF', 'SL 115'), ('5', '10131', 'B03', '1', '40', '3', '2018', 'B', '1300', '1500', 'MTF', 'SL 115'),
('6', '10132', 'C02', '1', '60', '3', '2018', 'C', '1100', '1300', 'MTR', 'SL 402'), ('7', '10133', 'D03', '1', '40', '1', '2018', 'D', '1200', '1500', 'W', 'GH 101');
